11/29/2023 11:25:49 - INFO - pixel.data.rendering.rendering_utils - loading text renderer configuration file https://huggingface.co/Team-PIXEL/pixel-base/resolve/main/text_renderer_config.json from cache at /home/stefania/.cache/huggingface/transformers/892d6a02d7c441000de399de59ed70d943a81f7b0f536523b4af1111677a8508.e332b34c9c05756dd4aa51d8fa33461dbd79604752296d185f03f8004db30700
11/29/2023 11:25:49 - INFO - pixel.data.rendering.rendering_utils - loading font file https://huggingface.co/Team-PIXEL/pixel-base/resolve/main/GoNotoCurrent.ttf from cache at /home/stefania/.cache/huggingface/transformers/49e6dc219d1a1a1c9236acaf05a48b542002016a6dc877ee72baab085a84257b.3f28e7f4b38e1efe1b6da4a3732404c19d4c6a614ff32dce90a251e293d4ce58
11/29/2023 11:25:49 - INFO - pixel.data.rendering.pygame_renderer - Loading font from /home/stefania/.cache/huggingface/transformers/49e6dc219d1a1a1c9236acaf05a48b542002016a6dc877ee72baab085a84257b.3f28e7f4b38e1efe1b6da4a3732404c19d4c6a614ff32dce90a251e293d4ce58
11/29/2023 11:25:49 - INFO - pixel.data.rendering.rendering_utils - Text renderer PyGameTextRenderer {
  "background_color": "white",
  "dpi": 120,
  "font_color": "black",
  "font_file": "49e6dc219d1a1a1c9236acaf05a48b542002016a6dc877ee72baab085a84257b.3f28e7f4b38e1efe1b6da4a3732404c19d4c6a614ff32dce90a251e293d4ce58",
  "font_size": 8,
  "max_seq_length": 256,
  "pad_size": 3,
  "pixels_per_patch": 16,
  "text_renderer_type": "PyGameTextRenderer"
}
11/29/2023 11:25:50 - INFO - pixel.utils.modeling - Truncating position embeddings to 256
11/29/2023 11:25:50 - INFO - pixel.utils.modeling - Truncating decoder position embeddings to 256
11/29/2023 11:25:50 - INFO - __main__ - Running PIXEL masked autoencoding with pixel reconstruction
11/29/2023 11:25:50 - INFO - __main__ - Applying span masking with "max_span_length = 6" , "cumulative_span_weights = [0.2, 0.4, 0.6, 0.8, 0.9, 1.0]"  and "spacing = span"
11/29/2023 11:25:50 - INFO - __main__ - Masked count: 64, ratio = 0.2500
11/29/2023 11:25:50 - INFO - __main__ - Training mode: True
Traceback (most recent call last):
  File "/media/stefania/A650A6F450A6C9FF/Work/RUG/Master/MA Thesis/pixel-semantic/scripts/visualization/visualize_pixel_uncertainty.py", line 256, in <module>
    main(parsed_args)
  File "/media/stefania/A650A6F450A6C9FF/Work/RUG/Master/MA Thesis/pixel-semantic/scripts/visualization/visualize_pixel_uncertainty.py", line 205, in main
    plt.imshow(confidence_map, cmap='Greens')
  File "/home/stefania/anaconda3/envs/pixel-env/lib/python3.9/site-packages/matplotlib/pyplot.py", line 3346, in imshow
    __ret = gca().imshow(
  File "/home/stefania/anaconda3/envs/pixel-env/lib/python3.9/site-packages/matplotlib/__init__.py", line 1465, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/stefania/anaconda3/envs/pixel-env/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5756, in imshow
    im.set_data(X)
  File "/home/stefania/anaconda3/envs/pixel-env/lib/python3.9/site-packages/matplotlib/image.py", line 723, in set_data
    self._A = self._normalize_image_array(A)
  File "/home/stefania/anaconda3/envs/pixel-env/lib/python3.9/site-packages/matplotlib/image.py", line 693, in _normalize_image_array
    raise TypeError(f"Invalid shape {A.shape} for image data")
TypeError: Invalid shape (3, 256, 256) for image data